.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2017 Gaurav Juvekar <gauravjuvekar@gmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH coloredlogs 1 "February 01 2017"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
coloredlogs \- colored logs for Python logging module
.SH SYNOPSIS
.B coloredlogs
.RI [ OPTIONS ]
.RI [ ARGS ]
.br
.SH DESCRIPTION
\fBcoloredlogs\fP is a program that converts the output of any command
containing ANSI escape sequences to HTML. It also includes a demo for the
coloredlogs Python module.
.SH OPTIONS
This program follow the usual GNU command line syntax, with long options
starting with two dashes (`-').  A summary of options is included below.
.TP
.B \-h, \-\-help
Show this message and exit.
.TP
.B \-c, \-\-convert, \-\-to\-html
Capture the output of an external command (given by the positional
arguments \fIARGS\fR) and convert ANSI escape sequences in the output to HTML.
.br
If the \fBcoloredlogs\fR program is attached to an interactive terminal it will
write the generated HTML to a temporary file and open that file in a web
browser, otherwise the generated HTML will be written to standard output.
.TP
.B \-d, \-\-demo
Perform a simple demonstration of the coloredlogs package to show the colored
logging on an interactive terminal.
